### ISSUE TITLE
Develop model and identification strategy

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/PhoneAddiction#13]
The goal of this issue is to develop the model and identification strategy.

I have pushed a very rough initial outline [here](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf).
The lyx file is [here](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/source/PhoneAddiction_Model.lyx).

Matt's comments on the initial file are here: [PhoneAddiction_Model-mg.pdf](https://github.com/huntallcott/PhoneAddiction/files/2518906/PhoneAddiction_Model-mg.pdf)

@lenasong, we were wondering if you would be willing to work on advancing this model aspect of things. You'll see in the intro to the pdf that I listed some papers to read and a plan for next steps.

I think we'll learn a lot from doing this. I also have the sense that there is a real appetite for an experiment that would cleanly identify habit formation and present bias in a field experiment setting.

****
@gentzkow's main comment on the rough initial outline was about how present bias is identified. Let's discuss that briefly. 
Here are the primary ways that present bias is identified in the literature, obviously some of which overlap in various ways:
1. Preference reversals (read and van leeuwen, augenblick, niederle, sprenger, and many others)
2. Biased beliefs about future behavior (identifies betahat minus beta only)
3. Selection into dominated contracts (shui and ausubel, dellavigna and malmendier 2006)
4. Effort cycles: Kaur/Kremer/Mullainathan, Shapiro (2006) SNAP daily discount rate paper. 
5. Demand for commitment (Ashraf, Karlan, Yin) (Identifies beta only; need more than just the fact of demand for commitment to estimate betahat)

(I put all these papers in the Lit folder for reference.)

My thinking has been that our best bet here is to identify present bias using a version of selection into dominated contracts. We see people choose some restriction in advance (stay under 60 minutes in our pilot design, or a tax of $X per minute in the model pdf), and then they later choose behavior. If you look at their realized behavior, they would have been better off financially (and from the perspective of the utility of the present self) had they chosen the flat payment instead of the restriction. To precisely calculate the beta, you then need to calculate the utility loss, which is what I outline in words in the doc. Matt expresses concern that this calculation is messy.

I see this as being broadly analogous to Shui and Ausubel, who show that people select into teaser rates but, ex-post given their borrowing behavior, would have been better off had they chosen a different contract.

@gentzkow or @lenasong do you have a better thought on this? Unless there is a major conceptual disagreement, it seems like the next step is for @lenasong to dive in as prescribed in the pdf.

**Comment by lenasong** [comment]
@huntallcott cool! I can start working on this next Monday and will come back with questions/comments.

**Comment by gentzkow** [comment]
Sounds good to me. Explanation above has made me more positive about this approach than I was when I first read the doc. I think @lenasong can proceed and I'll keep thinking about it as we go along.

**Comment by lenasong** [comment]
Wanted to give a quick update that I'm still working on this. I will have more time in the next few days as we are wrapping up the logistics for the pilot and will have some basic derivations done by early next week.

**Comment by lenasong** [comment]
I've posted an updated [model](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf) with the first steps solved, including updates on:
-allowing for exogenous initial stock of habit s1, instead of 0
-WTP
-identification of demand slope, direct effect of habit on demand, and amount of temptation 
-the set-up for partially naive temptation and habit formation - @huntallcott @gentzkow would love to hear your thoughts on what our next steps are for this 

I like the new MPL design with fixed payment and price/minute of usage, to get demand directly. We could pitch this to participants as a "phone time plan" - contract vs. pay-as-you-go. They choose between a fixed payment of $F to use unlimited phone time, or $p for each minute. 

Should we also somehow incorporate our pilot MPL? It's like a pre-paid plan - $Y for f minutes of phone use, and is dominated by $Y/f for each minute. When deciding between pre-paid vs. pay-as-you-go for a non-temptation good, a person would not choose the pre-paid plan; whereas when deciding for a temptation good, pre-paid might be chosen. We could even explore variation across phone categories, e.g. social networking is more of a temptation good than productivity. This approach of course has the same issue as demand for commitment as @huntallcott outlined above.

I also outlined a few other experimental design ideas in the discussion section.

**Comment by gentzkow** [comment]
Thanks @lenasong. This looks like good progress.

The biggest question for me with this approach is how we're estimating \beta. If I understand correctly, we're getting this by looking at how the response of period 1 consumption to p_1 compares to what we would expect given the other parameters. If the response is very high, we infer she must not weight the habit formation at all so beta=0. If the response is exactly what we would expect from a forward looking agent who weights future consumption equally we infer beta=1. 

This seems correct given the model, but also fragile. Our estimate of beta would seem sensitive to:
1. Deviation from perfectly forward looking behavior / sophistication
2. Anything that causes the marginal utility term \omega to be different in the two periods
3. Uncertainty / misprediction in habit formation \phi
4. The fact that we are assuming the world ends after two periods; in reality it continues which means our expression for the period 2 elasticity is not quite right

Also, am I right that we're not using the WTP numbers F_1 and F_2 at all in the identification of beta?

Seems like it might be worth some more work to see if it's possible to identify beta using @huntallcott's original idea of looking for dominated choices. My conjecture would be that that may give us an approach more robust to at least some of (1)-(4).

Happy to discuss partially naive temptation and habit formation further once we resolve this.

**Comment by gentzkow** [comment]
@huntallcott @lenasong One other note: Re-reading some of the lit, I'm reminded that a key test of forward looking behavior in Gruber-Koszegi, Becker-Grossman-Murphy, etc. is whether present consumption responds to expected future price changes. Seems like our current two-period two-price setup is well designed to evaluate that directly.

**Comment by huntallcott** [comment]
@lenasong @gentzkow a couple of additional thoughts from this morning:
1. Discrete vs. continuous choice
  - As @lenasong pointed out, we should keep in the back of our minds that the other experimental design option is to pay people F to keep minutes below some threshold, as in the pilot. 
  - One thing to flag is that the discrete choice could be a lot easier to explain to people, and could thus reduce noise in our estimates. Right now we are assuming that people can work out f*(p) \times p and compare that to F; it seems a lot easier just to figure out whether I'm willing to keep social media use under 20 minutes a day.
2. Identifying partial naivete.
  - I think that the best way to do this is to elicit beliefs and compare beliefs to reality. (The only alternative I see is functional form restrictions, but Shui and Ausubel's paper makes it really clear how both naivete and sophistication predict selection into dominated contracts, and how you need specific functional form restrictions to separate them.) 
  - So in the continuous choice case, we'd tell people how much they used historically, then ask, "how many minutes would you use your phone if we gave you p*?" This we can incentivize slightly if we want, as discussed in Augenblick and Rabin (2018).
  - In the discrete restriction case, we'd ask, "what do you think is the probability that you can keep your usage below 20 minutes per day?"
3. Identifying naive vs. rational habit formation. 
  - I actually don't particularly like the Gruber-Koszegi test of whether consumption responds to expected future price changes. Instead, I prefer the FB approach of measuring F* in advance and comparing to its eventual realization. This is for two reasons:
     a. People have to have a lot of sophistication to start reducing their consumption now in response to a future price change. Somehow the Facebook double-WTA elicitation approach seems like it requires less sophistication to test the same thing.
    b. The FB approach is robust to people perceiving some probability that they drop out of the experiment or that for whatever reason the promised price change won’t happen. This is a consideration in Natalia Rigol et al.’s hand-washing paper – they need to spend a lot of time establishing that they correctly conveyed to subjects that prices were going to go up.
4. This is slightly separate, but it's worth thinking about exactly what we want to get out of this model. Another option is to not focus so sharply on identifying structural parameters. 
   - We could show very interesting evidence of demand for commitment by just getting a large sample of college students and having them send us info (screenshots and self-reports) about how they are using their screen time apps. The fact of using those apps at baseline is demand for commitment. This is probably very cheap (it would just be a one-shot survey), and I think we should consider doing it regardless of what else we do.
  - We could show some evidence of learning/persistence/habit formation by simply encouraging a randomly selected treatment group to use their screentime app for awhile and then removing the encouragement, then measuring long-term effects.
The benefit of this study design is that it feels less artefactual/more realistic than this design required to identify structural parameters. The main benefit I see of identifying structural parameters is that referees may reward us for doing something complicated.

**Comment by gentzkow** [comment]
Good thoughts.

I agree about (1)-(2).

On (3), I agree that the FB version is a better way to get at sophistication about habit formation. I think the price effect is of independent interest, though. Becker and Murphy highlight this as the key test of the rational addiction model, and we'd have the potential to provide one of the cleaner tests. If we found that people do anticipate habit formation in the FB version but yet don't respond to future prices, that would be interesting. I agree that that pattern seems totally sensible as adjusting current behavior in anticipation requires a lot of sophistication.

(4) is almost exactly what my undergrad advisee Ruru is doing for her thesis. She's surveying students about use / knowledge of app limits then nudging people to try them out, then looking at long-term impacts. 

That doesn't prevent us from incorporating some of this in our study as well, but we should be careful. One option would be to fold some of this in and offer to make Ruru a co-author.

I don't think we should do anything just to be complicated. But I think there is high value to being able to say we can separate / identify / quantify different behavioral mechanisms in a rigorous way.

**Comment by lenasong** [comment]
@huntallcott @gentzkow thanks for the comments. I've updated notes on the [model](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf) with additional steps on identification of beta following Hunt's outline using F*.  This would, however, require identification of additional parameters (MU of other good, and intercept of MU of phone). 

I also included one other possible formulation, which compares the phone usage preferred by time-1 vs. time-0 self.  One way we could do it is to 
1) elicit number of hours under continuous choice, by asking "how many minutes would you use your phone if we gave you p*?" This gets time-1 preferred usage X from time-0 perspective 
2) offer a soft commitment device "do you want to pre-pay for X minutes for p* X dollars? If you use less than X minutes, you will be charged p* for each minute. If you use more than X minutes, you will receive no rewards at all". This gets time-0 preferred usage. 

Willingness to pre-pay for X or lower indicates beta<1. 

This approach, however, also relies on identification of other parameters, and these additional questions could make the WTA exercise too complicated.

**Comment by gentzkow** [comment]
Thanks @lenasong. The model note linked above is the older version dated Nov 12. Maybe you didn't commit the new PDF?

**Comment by huntallcott** [comment]
Hi @lenasong @gentzkow,
I thought more about some experimental design issues this morning.
1. After some emailing with Lena, it seems to me that identification of temptation is going to be tricky given the presence of the built-in screen time controls. These controls are a soft commitment that allows you to make it a bit harder on your future self if you go over some limit. *For the impact evaluation*, it seems like we do want to facilitate people actually limiting their use, which could likely involve coaching people on how to use those screen time controls. Thus, we hope to not see many people choosing a limitation and then ex-post exceeding that limitation. In our current model, that's interpreted as lack of temptation, but in reality, it is correctly interpreted as temptation plus coaching on a soft commitment device.
2. I'm leaning even more strongly toward sticking with the pilot's design of a maximum time use limit instead of a price. I do think we'll see more selection into ex-post dominated contracts in the price design, but (as we agreed above) this could just be due to confusion and forgetting, and I also add that this would be bad *for the impact evaluation* if we see lots of people choosing to impose a price on themselves but then ignoring that price and using lots of social media time. 
3. I started an [experimental design google doc](https://docs.google.com/document/d/1WH9EAjsdJhLjE0jzieUN4UgSiaR3ug8kdIgyjVhBfGw/edit?usp=sharing) which I think could supersede the pilot experimental design document. 
4. In that doc, I highlight another way to identify temptation, which will be analogous to the food stamp cycle/effort cycle identification strategy. If we give people a max time use limit, the treatment group will tend to use up their minutes early on. We would either need to give up on identifying an exact beta or figure out some additional strategy that would require us to know the elasticity of inter-temporal substitution. (Aside: I guess we could get this by paying people to use social media only early in the day, if the app works out in #14.)
5. My point 4 might lead us to a more reduced form paper that rejects a null of no temptation instead of actually estimating a temptation parameter. I note that Kaur, Kremer, and Mullainathan (2015) doesn't actually estimate a temptation parameter -- they just have a test of temptation -- and Shapiro (2005) has calibrations but doesn't want to take much of a stand on the elasticity of intertemporal substitution. @gentzkow, above you said that there is value to separating/identifying/quantifying different behavioral models, and I guess the question is what value we place on separating/cleanly identifying vs. actually *quantifying* the parameters.

**Comment by gentzkow** [comment]
@huntallcott @lenasong 

I'm not sure how concerned to be about (1). One way to think about it is that we will be identifying the temptation parameters given the baseline rate of commitment device / monitoring usage. That would presumably be less temptation than if we fixed such usage at zero, but it's arguably the more interesting parameter for policy. I suspect baseline usage is low enough that the gap between the two is not too large.

I like the idea of using effort cycles, and I think the Kaur et al [paper](https://www.journals.uchicago.edu/doi/abs/10.1086/683822) is in general a nice model to follow. One thought is that this approach would be a lot more convincing if we could randomly vary the time of day that your commitment clock resets. That should be feasible with the last-24-hours report on iOS, right? 

I also wouldn't give up on ex post dominated contracts. I wonder if with the right framing we couldn't get some people to actually select >$0 penalties for exceeding time limits over $0 penalties. We could say, for example, that we give you a budget of money and you can choose how much of it to pledge to help make your time limit commitment "stick".

I am not deeply committed to point estimates of parameters rather than just testing signs. But I have a general intuition that we should be ambitious and keep pushing for a framework that has a lot of flexibility and power so we can estimate the full range of things we'd be interested in in the most robust possible way.

I was thinking more today about the parental control [features](https://9to5mac.com/2018/06/21/ios-12-how-to-set-up-screen-time-as-a-parent-on-a-childs-iphone-or-ipad/) on screen time. In principle, these make it possible to (i) robustly monitor use; (ii) make time limit commitments binding (since you need a password to override them). It is not feasible for us to set ourselves up as "parents" for all participants. Among other things, I think the family sharing feature has a limit of 6 family members. But two things seem worth keeping in mind:

(A) It might be we could set up a peer-to-peer monitoring system. E.g., each participant could serve as monitor (i.e., parent in screen time) for one other participant. Or, alternatively, we could separately enroll people to be monitors who are not subjects in the experiment and have each of them track 6 other participants. Of course people could collude w/ monitors, but we could spot check this in various ways (e.g., by randomly pinging participants to send us screen shot of usage as of the current period).

(B) We could try pitching this as a very specific request to Apple. Unlikely they'd agree to play ball, but not impossible since this presumably would have low cost to them -- e.g., they might just need to give us permission to set up a bunch of separate apple IDs to use for monitoring and/or turn off the 6 person limit.

Before worrying too much about the details of this, I think it would be worth sketching out what the design / identification would look like if we did have unlimited access to this feature. Seems like it would make identification via demand for commitment devices more powerful. Also seems like we could have a version of ex post dominated contracts a la [Shui & Ausubel](https://eml.berkeley.edu/~webfac/dellavigna/e218_f05/ausubel.pdf) by allowing people to choose a price they have to pay each time the override a daily limit.

**Comment by huntallcott** [comment]
Some thoughts:
1. As Michael found in #12, it looks like there is quite a bit of self-reported usage of at least parts of the screen time app.
2. If parental controls turns out to be feasible, you could imagine two treatment arms, one with forced compliance via parental controls and one without.
3. I actually think that identification of partially naive temptation is *harder* if we implement forced compliance with parental controls than if we just incentivize people without the forced compliance. All of the forced compliance designs (e.g. Reed and Van Leeuwen, Augenblick/Niederle/Sprenger, etc.) have a now vs. later decision, whereas for us, all of consumption is in the future. Instead, our "selection into dominated contracts" identification comes from people opting into a contingent payment for lower usage *and then using so much in the moment that they lose that payment.* Two arms (with vs. without forced compliance) could still be interesting, though, and forced commitment gives higher power in the impact evaluation.

**Comment by lenasong** [comment]
@huntallcott  will do - thanks for the outline. @michael-butler1994 @gentzkow I've started an [agenda](https://docs.google.com/document/d/1uF5U7wWL5feaprPx-c65ZvAv14yPVABXF7zSgaGmmMM/edit?usp=sharing) for our Monday meeting and will summarize any progress here.

**Comment by huntallcott** [comment]
@lenasong @michael-butler1994 @gentzkow,
Yesterday I think we tentatively decided that we want to focus on the max minutes design instead of the price per minute design because (i) it's easier for people to understand, and (ii) it will probably have larger impacts on actual behavior. But we also foresee that this will make it harder to estimate the temptation parameter.

Another option is to think about how we make the price clear to people. 
1. after the price is assigned during the survey, give examples of how their usage adds up, e.g. “at $5 per hour, if you keep your usage to 1 hour per day instead of your usual 2 hours per day over next month, you’ll earn $300. If you keep your usage to 30 minutes per day instead of your usual 2 hours per day, you’ll earn $450. 
2.  during the survey, ask people how much they plan to use their phone given their price offer.
3. give regular updates on how they are doing relative to their plan. E.g. a one-per-several-days pop-up saying “remember, you lose $5 for every hour that you use your phone. So far this week you’ve used your phone for 6 hours, and you’ve lost $30. You’re over your planned earnings by $X”

Do you think there is a way to make this understandable and effective? If so then I think we should push in that direction.

Note that price also has issues around cost and non-linearities. By that I mean, the best way to do this is to offer people $5 for every hour they use less than their average, where their average is like the "intercept" of a pricing function. But (i) this introduces a non-linear price in the event that people end up using more than their average, and (ii) there might be a lot of inframarginal minutes if everybody restricts their usage to half of their average. So in designing the price we need to trade off setting a higher "intercept" with the fact that a higher "intercept" means that there are more inframarginal minutes.

**Comment by gentzkow** [comment]
I like your proposal for the price approach. The key to me is the ability to send frequent notifications. So long as we can remind people frequently about usage relative to a target we should be in good shape.

@huntallcott: Are there any good touch points here in the energy literature? I would have thought experiments varying electricity prices would face similar issues.

An advantage of price beyond estimation is that there's less risk that lots of our sample will end up far from the discrete threshold and so face zero incentive.

We should be able to calibrate the pricing function using pilot results. And we can try again the price discrimination strategies we experimented with in SocialMediaEffects.

**Comment by huntallcott** [comment]
@gentzkow yes there are non-linear pricing papers (Reiss and White, Ito, others) looking at block pricing schedules, but many papers just abstract away from the issue and/or focus on settings where the price structure is just fixed + constant marginal. 
The papers I've been concerned about are more about how to estimate partially naive present bias in dynamic models. The most recent one to look at is Laibson et al 2015 (in the Literature folder) and cites therein including Harris and Laibson's 2001 Econometrica paper. Sophistication often gives unreliable estimates, as you see discussed in Section 6.1 of the 2015 paper, but I think we all have the intuition that having prices instead of a max minute restriction may help us a lot.

**Comment by huntallcott** [comment]
And oh yes, sorry there are papers on providing info about time-varying prices, including an old paper I worked on, a paper in AER by Jessoe and Rapson, and obviously the work on cell phones by Grubb. But I think the basic finding is that providing info on prices helps people to understand prices ...

**Comment by lenasong** [comment]
@huntallcott @gentzkow the new price approach sounds good. Should we test it out in the pilot we are starting? 

Couple of thoughts:

- Do we want to do price/minute or price/hour? It seems easier (and more substantial) to talk about price/hour, but we could make it clear that they will be paid pro rata?


- What about setting the "intercept" to be a fixed level L for everyone, instead of the personal average? This has a few advantages 1) avoid problems with measured personal average (e.g. recruitment happens at a time participants have a lot of free time and therefore use their phone a lot more than usual)  2) I don't think gaming (in the sense of participants using their phone excessively to have a high average) is a big concern if we use the average before WTA elicitation. We can't have a practice WTA at baseline though. 3) fairness across subjects - a phone addict and a hermit make very different sums for restricting their phone use to the same level  4) easier to compare fixed payment F across subjects - everyone is answering their value at L instead of at their own average. I'm thinking to do the WTA demand curve equivalent to Figure 5 of [Brynjolfsson, Eggers, and Gannamaneni (2018)](https://www.dropbox.com/s/evgaw8p45wegzqj/Brynjolfsson%2C%20Eggers%2C%20and%20Gannamaneni%202018%20-Using%20Massive%20Online%20choice%20experiment.pdf?dl=0). 

We could set L to be some high number (say 75 percentile of phone usage in our previous pilot) and ask participants to choose between $F for placing no restrictions vs earn $p for each hour they use less than L (every day or on average per day).

Thoughts? I can start drafting these WTA questions to prepare for our pilot next week.

**Comment by huntallcott** [comment]
@lenasong just saw this after my other post. Yes this looks good for the pilot. Thanks.

**Comment by gentzkow** [comment]
@huntallcott @lenasong: One of the things we learned from the post-endline interviews in SocialMediaEffects is that people had a lot of time understanding the BDM mechanism. Does that give us any pause with our current "Option A vs Option B" approach here? I'm a bit concerned that this will also be confusing for people, and we might want to think about ways to simplify further.

I have no problem proceeding w/ the current version for this pilot. If we get the sense confusion is a real problem we could revisit then.

**Comment by huntallcott** [comment]
@gentzkow great question.
I think we are right to have a general wariness of WTA elicitation using BDM or MPL. 
But I believe (also from parallel conversations with Dmitry Taubinsky) that MPL is better than BDM for two reasons:
1. With MPL, it's a bit easier to explain that you should answer honestly, and whereas with BDM it's easier to start thinking that you're making a strategically non-truthful bid against the computer.
2. It's easier for people to answer questions of the form, "would I buy this for X," compared to "what is my reservation price?"

The problem that I do think we need to really solve is anchoring. So Lena, the problem is that if we offer the treatment group money to reduce, does that offer have a causal impact on how much they think they should be paid in the future, independent of actual habit formation.  This then confounds the habit formation estimates. 
It seems that there are several options:
A. Measure habit formation only through actual phone usage, instead of through WTA, and:
B1: still identify unanticipated habit formation from changes in WTA (which I'm worried about), or:
B2: go back to identifying unanticipated habit formation from how changes in usage respond to future promised price changes (which I don't like).

**Comment by huntallcott** [comment]
@lenasong,
Would you be interested to take a stab at completing the two-period model? I think there are two things remaining: partially naïve habit formation, partially naïve temptation. 

1. Unless Matt objects, let’s get people’s predicted habit formation from an improved version of the Facebook design. For all subjects, in the survey before period t, we are doing MPLs for restrictions in period t. *Before* that MPL for period t, for all subjects, we give them two MPLs for period t+1, one to be used if we restrict you in t, and another to be used if we don’t restrict you in t. The difference between those two tells us people’s perceived habit formation parameter. We could address the design specifics later, but the key for the model writeup lyx file is that we would get an F* for future periods conditional on a p in the current period.

2. For partially naive temptation, we add in that we will have each person's beliefs about f in an upcoming period, conditional on p. beta - betahat is determined by the difference between actual f and predicted f. 

Note: if it helps keep the algebra cleaner, I'd be fine with solving the partially naive temptation part in a one-period model and the habit formation part in a two-period model. This is just so that we have a clean accounting of our identification in a simple model. Once we finish this we need to go to something fully dynamic, and I have ideas there for when the time comes.

@lenasong what do you think about adding in 1 and 2 if you have some time over the next couple of days?

**Comment by lenasong** [comment]
@huntallcott I'm back from Atlanta. Working on this in the next couple of days.

**Comment by lenasong** [comment]
@huntallcott @gentzkow I've updated the [model ](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf)with partially naïve habit formation and temptation. This is in Section 2F and 2G, starting at page 8.

As Hunt suggested, to keep the algebra clean I wrote up how we could identify betahat/beta in a one-period model and projection bias alpha in a two-period model. 

Quick comments:
- betahat/beta could be identified by comparing the effect of a price change on predicted vs. actual usage (i.e. what participants answer at t=0 when asked "what percent do you think you would reduce your phone usage if price is imposed" vs actual reduction)
- we could identify alpha in a couple of different ways: difference in predicted vs. actual usage in second period, difference in WTA to restrict time-2 usage at time-0 vs. time-1. 
- expression of F* (relabeled as G in the write-up) for future period conditional on p in current period is unfortunately very messy
- however, I did manage to get a relatively clean expression for the difference in G (change in WTA) at t=0 for restriction at t=2, conditional on price imposed in t=1. This is equation (30).

Thoughts? Let me know if anything is unclear.

**Comment by huntallcott** [comment]
@lenasong this is great.
1. Minor but shouldn't you use \beta instead of \bar{\beta} just to be standard?
2. You suggested asking "how much do you think you *should* consume later at t=1?" I think this is the right idea for suggestive evidence (e.g. our questions like "do you want to use your phone less?"), but for the actual paper referees will want us to actually estimate demand for commitment through our MPL.
3. On habit formation, I like your point that we can get alpha in different ways. I have two problems with predicting usage: (i) that also has to be made contingent on p2 given that most people with p1>0 we will also randomize into p2>0 for the purposes of high-powered impact evaluation and habit formation estimates, so now we're asking "how much would you use if you had p1 = X and p2 = Y, and it's a pretty difficult contingent problem, and (ii) we want to use unincentivized beliefs as little as possible (for sophisticated present bias we have no alternative to belief elicitation, but here we do have the difference in WTA to use. So I suspect we should focus on getting projection bias from the difference in WTA, as we did with Facebook.

Let's have @gentzkow take a look when he has a minute. Then as a next step we can consider a dynamic model.

Thanks again for your great work on this.

**Comment by lenasong** [comment]
@huntallcott agreed. From what I understand, equation (31) should provide the projection bias identification equivalent to that in the FB project. Only wish the expression was as clean!

I'm leaving for fieldwork in Ghana and will be back next weekend. Look forward to @gentzkow's feedback and working on the dynamic model next next week.

**Comment by gentzkow** [comment]
Sorry for the slow reply! Hoping to get to this soon.

**Comment by gentzkow** [comment]
Thanks @lenasong for the great work on the model and @huntallcott for the tips on the paper.

Here are some thoughts on the model.

1. I like the idea of supplementing analysis based on WTA with prediction questions. The Acland and Levy paper uses prediction questions in this way. It seems to me like if what we're trying to get at is misprediction looking at directly how subjects predict is a good idea. I'm pretty skeptical of fine inference based on WTA after the FB experiment (even if we don't screw it up) so I like the idea of having multiple pieces of evidence we can triangulate even if some of them are unincentivized / may make referees grumpy.

2. My undergrad student Ruru Hoong is doing a somewhat related experiment where she has people predict their phone usage, compares this to actual phone usage, and then perturbs usage by nudging people to experiment with screen time restrictions. She also has a module looking at what people know about their privacy restrictions. Preliminary results from her pilot are here -- too small for the results to mean anything but it can give you a sense of the design.
[01112019_Pilot_Write_Up_draft.pdf](https://github.com/huntallcott/PhoneAddiction/files/2785821/01112019_Pilot_Write_Up_draft.pdf)

3. On the basic model identification, I am concerned that many people may not do the kind of sophisticated forward-looking adjustment to habit formation that the model predicts (e.g., adjusting response to t=1 price to account for the fact that period 1 consumption feeds into period 2 habit stock). I also think some of these fine predictions are sensitive to the quadratic functional form. I think a good way to make what we are doing more robust would be to introduce an additional parameter (call it rho for now) which simply discounts everything in period 2. rho=1 is the special case where people are perfectly myopic. I think we should restrict ourselves to designs where rho is identified separately from the other parameters and we can identify what we want even if rho=0. This forces us not to rely too much on sophisticated forward-looking behavior, and I think it means beta is no longer identified in the fragile way of equation (19).

4. Would we get some additional mileage by varying whether we tell people the realization of p2 before or after they choose period 1 consumption? Not totally clear to me but seems worth considering.

5. I agree that "what would be your ideal consumption" questions should be suggestive evidence only and not used in identification.

6. It's good to think about what are the key qualitative patterns we want to look at separately from the quantitative estimation exercise and make sure we think these are robustly pinned down, ideally with multiple corroborating pieces of evidence. Key things would seem to be:
* Responsiveness of period 1 consumption to period 1 price (elasticity)
* Responsiveness of period 2 consumption to period 1 price (habit / learning / state dep)
* Responsiveness of period 1 consumption to period 2 price (sophisticated habit response)
* Prediction of how period 2 consumption will change with period 1 price (projection / misprediction)
* Demand for commitment (temptation?)
* Impact of reduced consumption on other outcomes (happiness, information, etc.)

**Comment by huntallcott** [comment]
Hi all-
I've been thinking more about this and have a couple of questions/observations:
1. I continue to think we want to avoid non-linear pricing schemes, and instead focus our price mechanism as being something like "$0.50 or $1 per hour you reduce relative to your baseline average over the next 20 days." So @michael-butler1994 in one of your excellent emails to me, you proposed a non-linear pricing scheme which is cool but won't work well for the model, and similarly I want to make sure that @gentzkow's suggestion [here](https://github.com/huntallcott/PhoneAddiction/issues/14#issuecomment-459937461) is something we can actually model cleanly. Matt, you may have something in mind here for how to use that to actually estimate betahat and beta, but I don't quite see it yet.
2. I'm thinking about how to formally model this blocking technology that American Chris can develop. Here is a different way of implementing the blocking technology that I think we could model: 
   - The blocker is made available to a Blocker Treatment Group only, and not made available to a Blocker Control Group. 
   - People set their own blocking on their own blacklisted apps as they see fit.
   - One version of the blocker turns off apps after reaching the daily limit, but by clicking a button, you can open the app after a five minute Delay, as long as you open the app within five minutes after that. If you do open the app between 5-10 minutes after clicking the button, the blocker is off for the day. If you don't open the app by minute 10, the blocker is back on and you can again click the button to use after a five-minute delay.
  - The second version of the blocker is just a Reminder. When you reach the daily limit, it reminds you once that you've reached your daily limit, but by clicking a button, you can make the reminder go away and continue using the app. (This is optional but identifies another potentially interesting parameter below.)
3. Then you could imagine a model with many (e.g. 288 five-minute long) periods within a day, and beta, betahat, habit formation, and a new partially naive "automaticity" parameter. In each period, you draw a utility of consuming social media, and you consume if that utility is above a threshold. Under the automaticity parameter, you continue to consume in period t+1 if you were consuming in period t, unless your blocker reminds you.
4. Then the design is as follows:
  - Everyone receives MPL trading off a fixed payment vs. the subsidy for reducing overall phone minute consumption.
  - We elicit from everyone their predictions of overall phone minutes under the Subsidy.
  - The Subsidy Treatment Group receives the subsidy.
  - The Reminder, Delay, and Control Blocker groups are cross-randomized across the Subsidy Treatment and Subsidy Control group.
5. The Reminder Blocker identifies the automaticity parameter. We model the Delay Blocker as aligning the preferences of the long-run self and the present self. We hope that under the Delay Blocker condition, we see that people on average select into their payment maximizing contract. (and any deviations are because of ???). The effect of the Delay Blocker relative to nothing identifies beta. In the Blocker Control, the MPL choices and the predicted usage identify betahat and beta, as we have discussed. We anticipate the most reduction in the Delay Blocker + Subsidy cell.

Thoughts?
I wanted to get this out here before writing it down.

**Comment by gentzkow** [comment]
Thanks @huntallcott. I haven't fully thought through the details of identification here but let me give you some quick reactions.

1. From what I understand about the programming costs I think we should limit ourselves if possible to blocking restrictions that we set on our end rather than creating UI to allow people to control it themselves. That doesn't necessarily rule out what you are suggesting -- we could have delay blocking, reminders, etc. that people choose on our survey and that we then implement on their behalf. But it does mean there's value to keeping things simple.

2. My idea with the costly snooze button described [here](https://github.com/huntallcott/PhoneAddiction/issues/14#issuecomment-459937461) is that it seems like a good direct measure of both self control and naivité. Being willing to pay more to set a higher price for the snooze button would be a clear version of WTP for commitment.  We can ask people to predict how much they will use it in an incentivized way and then use deviations from the prediction to estimate naivité.

3. The idea of using delay to make the snooze decision non-tempting is very cool. I'd vote that we first get the design working without this and then consider adding it.

4. Seems like we should have reminders no matter what. This doesn't really interact w/ hard blocking.

**Comment by huntallcott** [comment]
@gentzkow @lenasong @michael-butler1994,
I have posted the revised identification document as promised. I'm sorry it took so long. I spoke with Acland, Levy, and Taubinsky about this stuff and needed to let thoughts settle. 
Two key things:
1. @gentzkow you'll see that while I love the costly snooze button and share your broad intuition as to the direction of the effects as you suggest above, I don't think that it's nearly as clean for identification of structural parameters due to the non-linear price and corner solutions. If you see a clean way to write this down, I would welcome you taking a stab at it. 
My other key intuition is this: if we like the blocker with a non-linear price, why not just use the blocker with a linear price?
2. I'm increasingly convinced that the blocker cannot be modeled structurally, and so we want to think of this as a reduced form intervention that just changes the demand curve. In light of that, I think that the key desiderata for the blocker are (i) what reduces consumption the most without generating attrition and (ii) secondarily, what might be interesting descriptively. Thus, my preferred blocker design is still the Delay Blocker with hidden off-switch, and I'd also add the Reminder Blocker with hidden off-switch to compare to the delay blocker in a reduced form treatment effects discussion.
3. Per your point 1 just above, I'd be happy to set up blocking restrictions on our end, but I think we do want to allow people to specify in Qualtrics what apps they have and what they want to block, as this generates interesting descriptive data about what are the most tempting apps.

**Comment by huntallcott** [comment]
@gentzkow @lenasong @michael-butler1994 ,
There is one additional thing worth highlighting from my conversations with Taubinsky and Matthew Levy. Both of them were quite focused on separation of habit formation (like a change in marginal utility) from learning. 
* Taubinsky's idea was to do some sort of cognitive task and measure whether Treatment vs. Control groups get rid of their phones during that task. This identifies whether people realize that their phone is distracting. Seemed tricky to implement and only captures one dimension of learning.
* Levy points out that the vacation period in Acland and Levy (2015) is nice. The vacation period basically re-breaks the exercise habit that had formed. This is evidence that the change was habit, not learning, because you would have expected a learning effect to last for longer. Perhaps we can look for the equivalent of vacation periods in our data, e.g. asking people when their semester ends.
* Levy's suggestion to us was to provide an incentive for one group to use the phone MORE. The post-incentive effects of an incentive to increase usage go in the opposite direction of the learning effect. I suspect that this is also infeasible because you could cheat by just leaving your phone on but not looking at it.
* In the end I fear that our best bet here is to ignore the issue in the structural model but do some mediation analysis to tease out learning, i.e. looking at whether changes in beliefs (from survey questions at endline) about the benefits and costs of phone usage mediate the treatment effect on usage.
Thoughts?

**Comment by gentzkow** [comment]
Thanks! A first reaction is: Can you give me the pitch for why habit formation vs. learning is a super interesting distinction here? I'm inclined to agree that it's interesting, but the two seem to blur together to some extent -- a realistic model of learning includes some forgetting, and once you have that the differences between the two are pretty delicate. From a policy point of view, what does it change if people are over-consuming because of habit formation or because they're misinformed? I guess the latter would suggest informational interventions could work; but then you might say you learn things by experience that are hard to learn just by being told the info.

* I agree the getting rid of phones idea is probably too tricky.

* On vacation periods, the idea would be to look for a vacation that occurs at some point post-experiment and see if there is more reversion to habit during the vacation? Or to look for a vacation within the treatment period?

* I agree that incentives to use phones more are going to be difficult due to the cheating problem.

* I agree with your final conclusion.

**Comment by huntallcott** [comment]
* Re: vacations, yes the idea is that they disrupt the habit.
* I'm not hung up on this distinction either, just sharing what others have said. I think that people who are really deep in these models want to make sure that we are applying the right model to the right phenomenon. If we are going to model this as a change in marginal utility, we hope that it's indeed a change in marginal utility, not information set. I think you and I are in agreement.
* Per my email, I await your response to my earlier post [here](https://github.com/huntallcott/PhoneAddiction/issues/13#issuecomment-461508344).

**Comment by lenasong** [comment]
@huntallcott @gentzkow @michael-butler1994 
I've added some notes in the [identification document ](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf) starting at page 6 in section 4.

This outlines the ideas we discussed in the meeting, including identification for betahat and demand for commitment by comparing the consumer surplus implied by predicted usage and the fixed payment participants choose in the MPL. See the lyx comments for some additional thoughts on identifying beta. It relates to changing the habit stock (and could be done possibly via vacation periods).

**Comment by gentzkow** [comment]
@huntallcott @lenasong Thanks for all the work on the identification doc. Here are some initial thoughts. Happy to discuss further. By default you can assume things I'm not mentioning here I agree with.

## Blockers

First off, I'm not 100% sure what the proposal is for the blocker condition. Is the idea that subjects in this condition are completely free to choose whether to use the blocker and if so what limits to impose on which apps? That sounds like a good approach to me. We could also think of ways to push or pay people to use the blocker as a way to increase treatment effects.

I'm not sure I understand the comment in III.A that we could just model the blocker as a different xi^b and omega^b. Varying those parameters changes them in the same way for both the current and future self. But the blocker provides a way for the present self to impose their preferences on the future self and so I'm not sure there's any xi^b and omega^b that would fit the effect for agents with beta<1.

I agree that we should not try to model the blockers structurally, and that we should treat those as ways to increase treatment effects + produce interesting reduced-form patterns.

I like the idea of the delay blocker and I suspect it may be good for increasing treatment effects. My main concern is along the lines of your subway example on p. 3.I can imagine situations where people really need to use an app immediately for some reason -- e.g., they want to look up an address that was posted on FB for somewhere they're going or they need to contact someone urgently who they only reach through FB -- and they will get mad at not having an easy way to dismiss the blocker. This could increase attrition / frustration.

If we did go with the delay blocker, I like the idea of allowing people to choose their preferred delay and also asking them to predict how often they're going to use it just like in my snooze blocker proposal.

I'm not seeing why the "snooze button blocker" is any worse from a modeling perspective than the delay blocker. In both cases it seems like we'd need to punt on modeling it. Both of these effectively induce a "non-linear price within day". Basically, a snooze button with a price of "wait 10 minutes" and a snooze button with a price of "$X" seem quite similar theoretically. But perhaps I'm misunderstanding something about the delay blocker.Modulo my possible misunderstanding, I continue to like the idea of the snooze button from the perspective of the descriptive evidence it would produce. A different version than the one described on p. 2 would let people freely choose their daily limit and price for snoozing. We could denominate the price in units of minutes (i.e., we'll adjust your payment as if you'd used 10 extra minutes). 

## Reminders

It sounds like the "reminder blocker" is equivalent to this snooze blocker when you choose a price of zero. I certainly have no objection to that.

I would vote that regardless of what we do with that we also include daily reminders (for everyone in the subsidy group) of where there usage is, how much money they're earning, etc. 

## Nonlinear Pricing

The issue @huntallcott mentions at the top of p. 2 (I.A item 1(c)) about the base usage rate being high enough that most people stay in the subsidy range seems important to me. Given the variance we've observed in usage, I think it would be *very* expensive to set this so it's a reasonable assumption that everyone will place Pr=0 on exceeding the base usage. Even if 80% of people stayed below, we'll still need to talk about how anticipating a 20% probability of being above would affect choices. And even if 99% of people stayed below it's possible that people misforecast this ex ante.

Bottom line is I think we're going to need to do something to deal with this nonlinear pricing no matter what. Given that, I wonder if we don't want to push harder on whether we can estimate the model with the non-linear price and then set the base usage rate to something lower and thereby save a lot of money.

## Identifying Demand for Commitment 

@lenasong I didn't quite understand what you wrote here on first glance. In I.A @huntallcott defines the EV to be the expected subsidy given usage beliefs -- i.e., the subsidy amount people would receive if their usage guess is correct. You define it as "how much the agent should be compensated by the difference in consumer surplus between zero price and price of p at t=1" -- sounds like this is the WTA of the future self. Maybe these are the same thing but I'm not seeing that. Can you clarify?

**Comment by huntallcott** [comment]
Great and thanks @gentzkow. Thoughts below.

### Blockers
1. Agree that we would let people set the blockers however they like and use that for descriptive evidence. In that case, ideally Chris’s app would have an interface that allows people to set the blockers directly on their phone, instead of in qualtrics. Do you all agree? (This is modulo my question in 9 below.)
2. Agreed with Matt’s second paragraph under Blockers. I should have said that to model the non-price aspects of the blockers, I would also model different beta and betahat, so beta^b and \hat{beta}^b, and I would expect that beta^b>beta and \hat{beta}^b>\hat{beta}.
3. Regarding attrition with the delay blocker, I would say (i) let’s just try it in a pilot, and (ii) I wonder if we should have two disable buttons in the app, one which disables the blocker for a day, and one which disables the blocker permanently.
4. The reason I think the “Snooze + Price Blocker” is worse than the non-price blockers (Reminder and Delay) is that it is literally a price. The second we have a price, we will need to model it as a price instead of something that shifts the demand curve. The non-linear price model would be unnecessarily complicated on top of the existing price structure proposed in the document. Of course, if we get rid of the subsidy for overall reductions as currently contemplated in the document, then I’d be happy to switch over to the Costly Snooze Button strategy, per my question in 9 below.

### Reminders
5. I agree with daily (or every other day) reminders, either by email or popup, about what their usage is and how much money they’re earning. One amendment is that I think we also want parallel reminders for the Subsidy Control group, so that those groups only differ by the price they are receiving.

### Nonlinear pricing
6. I respectfully disagree somewhat here. I think the point of a field experiment is to get us in a world where we can analyze the world using simple and believable statistics. My preferred approach for Subsidy Demand identification would be:
   - Longer baseline period to get a really good fix on average usage.
   - If needed, add 30-60 minutes to the pre-treatment average to set each individual’s subsidy baseline. I think we try to hit a sweet spot where \pi is sufficiently low and the budget isn’t too high. (See the lyx file for the definition of \pi.)
   - Do some serial correlation/budget/power calculations to find that sweet spot.
   - Use a linear pricing model for our main estimates as long as the \pi’s are sufficiently low.
   - Add an appendix model with non-linear pricing as a robustness check. I have just pushed a revised version of the identification doc with a sketch of how I would model this. It’s not terrible under the assumption I imposed. The key assumption is that \xi is revealed immediately at the beginning of the three-week period. At some top journals people might let this slide if pi and \hat(pi) are sufficiently small. At Ecma people might want some dynamic model of daily decisions. Lena, after we settle on “identifying demand for commitment” below, can you write out this model?


### Identifying demand for commitment
7. Yes, agree with @gentzkow that by EV of the subsidy I meant p \times ( f0 – fhat(betahat) ), and by CE of the subsidy I meant the fixed payment at which the participant is indifferent (in the MPL) between the fixed payment and the subsidy. Sorry to be confusing. Lena can you re-work that? It should look the same as an equation from the payday model I posted under the simple risk-neutral case.

8. I think we should also be able to drop the text beginning “In terms of survey language, this can be explained as follows” and just keep any additional survey design notes in Section 2.1.

9. So are we in agreement that we want to use the Subsidy Demand strategy instead of the Costly Snooze Button Strategy to identify betahat and beta? Having sketched the non-linear pricing model for the Subsidy Demand strategy, I am not quite as worried about the model for the Costly Snooze Button strategy as I had been before. I also clarified how I’d do the identification in 1.1 point 2 of the lyx file. I think that model would have daily demand for minutes with utility separable across days and habit stock constant within each three-week period for simplicity. \xi for each day is drawn from a known distribution, and once you hit the blocker threshold q you pay a non-price utility cost c if your usage exceeds that threshold (this will be needed to rationalize a bunch of days when usage = threshold), plus p for every hour above the threshold. 
  - Another Benefit of Costly Snooze: per my point in 6, it’s more plausible that \xi is known at the beginning of the day and fixed over the day than that it is known at the beginning of a three-week period and fixed over that period. 
   - Another Problem with Costly Snooze: Only restricts blacklisted apps instead of overall phone time. This leads to less descriptive stats on what people choose to block. We’d also have to think carefully about how to determine and load into Qualtrics each individual’s apps to be restricted.

**Comment by lenasong** [comment]
@huntallcott @gentzkow got it. I was working with a translation of both EV and CE - sorry for the confusion. The [identification file](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf) is updated with the corrections.

Let me know if this makes sense to you now and I can start working on nonlinear pricing.

**Comment by huntallcott** [comment]
@lenasong,
I just pushed a revision to the model.
1. I redefined the utility function so that beta and betahat are the standard Laibson notation. I had defined them differently and then confused myself. Some of my lyx comments should now be clearer.
2. I also redefined utility in a way such that long-run demand is a parallel shift from present self's demand. This should make the equations easier, because now we just have "behavioral Harberger trapezoids" and the formula is easy. I took a quick stab in one of the lyx comments.
3. Can you re-write from here? It should be very easy now.

**Comment by lenasong** [comment]
@huntallcott thanks for the helpful comments! We now have a clean identification of betahat and naivete in this simple set-up with parallel demand lines. Here's the updated [identification file](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf).

**Comment by huntallcott** [comment]
Great, thanks Lena! That's perfect. I just made some additional minor comments and pushed to the master. (I suggest you check out the diff from my latest commit.)

@gentzkow can you now take a look at this thread starting from my post [above](https://github.com/huntallcott/PhoneAddiction/issues/13#issuecomment-462824798)?

**Comment by gentzkow** [comment]
Yes. Thanks for the further thoughts and the revisions. Sounds like we agree about much of this. A few things still to resolve.

> The reason I think the “Snooze + Price Blocker” is worse than the non-price blockers (Reminder and Delay) is that it is literally a price.

I still don't see that. I don't see why having a monetary price is different from a delay price. In both cases the subject can always choose not to set any blockers at all. Therefore they should not affect the behavior of a fully rational agent. In both cases for a non-rational agent they shift the game between present and future self in a fairly complicated / nonlinear way that would be difficult to model explicitly.

> I respectfully disagree somewhat here. I think the point of a field experiment is to get us in a world where we can analyze the world using simple and believable statistics.

I fully agree about simple and believable statistics. I just think we need to be conscious of the tradeoff of $$/power we're making in order to buy close-to-linearity in the subsidy schedule. One way or another, I think what we will end up with is descriptive model-free patterns that tell the basic story combined with structural estimates that require stronger assumptions. I definitely don't think we want some kind of complicated dynamic model, but if we are going to need to model the non-linearity to some extent anyway we may not want to pay the cost of and extra 30-60 minutes for everybody. 

> So are we in agreement that we want to use the Subsidy Demand strategy instead of the Costly Snooze Button Strategy to identify betahat and beta?

I continue to think the best thing is if we can have both -- or at least have the costly snooze button as an additional set of descriptive facts even if we don't develop it as a source of identification for the structural parameters. 

---

I looked over the identification doc and it looks very good. (I haven't checked everything carefully.)

**Comment by huntallcott** [comment]
* Aside: I think we are going to need a dynamic model either way, due to the habit formation piece. 
* Lena: would you be willing to develop the non-linear price part of the model, using the sketch that I wrote in to the identification doc, section III.C? Hopefully it won’t be too hard. We can start with the model for the Subsidy Demand condition and then see if it looks easy to even extend it to model the Costly Snooze Button strategy.
* As Matt pointed out, it seems like the development cost of the Reminder + Price Blocker should be very small conditional on the development of the Reminder Blocker -- it's the same app functionality with different text. So I don't think this needs to hold up that functionality either way. @lenasong @michael-butler1994 can you work in #14 to get Chris going? We definitely want the Reminder Blocker with the ability to write in whatever text we want. I think we also want to try the Delay Blocker unless somebody objects. We need:
   - The ability to randomize across people whether we turn on the Reminder Blocker, Delay Blocker, or no Blocker at all, after the app has been downloaded, based on Qualtrics survey responses.
   - The ability to randomize across people the text they receive with the Delay Blocker (e.g. to tell them their snooze button price and/or remind them of their linear subsidy), also after the app has been downloaded. We can pre-specify the possible text during the development period, but we need each individual's specific text to be able to be turned on after downloading the app.
   - On the Delay Blocker, let people decide (in Qualtrics?) how long they want their delay to be, per Matt's point [here](https://github.com/huntallcott/PhoneAddiction/issues/13#issuecomment-462557832).
   - Does that make sense?

**Comment by lenasong** [comment]
Great. I'll start working on the non-linear price model and @michael-butler1994 and I will figure out the technical specs with Chris.

**Comment by lenasong** [comment]
@huntallcott @gentzkow 
I started working on an extension with nonlinear pricing (Section IV.C). From thinking about this and the discussion @michael-butler1994 and I had while drafting the technical specification for the blocker, I have a few questions:
- have we agreed on not modeling the blocker? How should we think about the blocker relative to the subsidy? There are measurement differences between these two: 
1) the blocker described [here ](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf)restricts social media apps only, while we are giving subsidies based on total phone use 
2) subsidies are given based on average daily use over the course of our study, whereas blocker restricts use over the course of a day

- should I think about all social media apps as one temptation good? The blocker setup we sent to Chris is as follows: usage limit is imposed over the total usage for a set of social media apps. When this limit is reached, blocker stops all apps in this set; and when a user snoozes, it opens up additional N minutes for total use over social media apps. This is a simple set-up to match the blocker outlined in our identification file - let me know if you had other designs in mind.

- With non-linear pricing and demand shifter, I'm not sure how we can identify naivete unless we elicit beliefs more carefully (e.g. "if you are in the subsidy condition") or make assumptions on the distribution of \xi. I'll spend more time looking into the nonlinear pricing literature and would love any pointers in the meantime.

**Comment by huntallcott** [comment]
Great Lena this is fantastic!
1. Equation (14) should have a betahat, not a beta, on the RHS, right?
2. @gentzkow, are you OK with this? (i) remember that this requires the strong assumption that there are no dynamics within the period, i.e. that at the beginning of the three-week incentive period you immediately know your value of \xi. I’m OK with it but somebody at e.g. Ecma might not be. (ii) I’m definitely not an expert on non-linear pricing, so there may be something I’m missing. 
3. Unless @gentzkow has some objection to the model, can you (Lena) also derive beta and the demand slope? Those should be easy but I want to have that written down.

On your bullets, in order:
* I think we have provisionally agreed to develop the Costly Snooze Button blocker and have it in the pilot, but not use it to estimate beta and betahat at least for now. Agreed on the two measurement differences you list. 
* In the model, I had been thinking about all phone use as a temptation good, and that's certainly how it reads now. 
   - Then to identify whether there are specific apps that people think are more tempting than others, we measure what apps people choose to restrict. 
   - And to identify which specific apps are actually more tempting than others (have lower beta), we would need to add additional questions: under the subsidy condition, how much do you think you would restrict your use of (i) social media apps (ii) all other apps. Then we can compare actual usage to perceived usage to get beta for different types of apps. Does that make sense? If so can you add it to the Qualtrics survey?
   - Thus, I think we want to set up all blockers so that we let people specify which apps they want to block, from a list that we will need to pre-populate somehow. (We expect more blocking will happen in the Subsidy Treatment Group, as this is pitched as a way to help people earn their subsidy.) Is Chris giving us the ability to let the users specify what apps they want to block?
* Thanks for looking into the nonlinear pricing literature. I think this will help. I know that Reiss and White (approx. 2002) is one reference from the electricity context, but it’s a bit different because most of this paper, as I recall, is about estimating from non-experimental data. Agree that we have to elicit beliefs more carefully, but two things: (i) we already needed to specify “if you’re in the subsidy condition. (ii) I think this is imminently doable: your nice model makes clear that the trick is that we need to elicit \overline(f), not just f, as well as pi. But that seems easy as long as people understand what we’re asking.

Thanks again. Full steam ahead.

**Comment by lenasong** [comment]
@huntallcott thanks for the feedback! I'm updating the [identification file](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf) with the typo corrected and an added section on deriving beta.

Also added the question on "how much do you think you would restrict your use of social media apps" to [baseline instrument](https://docs.google.com/document/d/1zb_x73LLjkU-TqPGcUHrS6ULYx-dPwCxV23nkPo4yCA/edit#) @michael-butler1994 started drafting. 

Quick clarification question: how much user flexibility do we want to give within Phone Dashboard? e.g. do we want to give users the ability to specify what individual apps to block? allow users to change blocking limit between surveys? We gave Chris a simple specification: user will decide what to block and limits within our Qualtrics survey (not the app) and can only use snooze/disable button between surveys. Let me know if you think additional flexibility is crucial and we can ask Chris if these features can be included. 

Related, how much do we care about understanding specific apps like Facebook and Snapchat, in addition to understanding a broad set of social media apps vs. set of all other apps? If our emphasis is over the category instead of specific apps, then we can shorten the surveys by giving participants a pre-determined set of social media apps, elicit beliefs on the entire set, and design the blocker and snooze button around the total usage for that fixed set.

**Comment by huntallcott** [comment]
@lenasong great. Comments:
1. Let me know when you're done deriving beta and the demand slope. To be clear: (i) by "demand slope", I mean the structural parameter \omega, and (ii) we want these in terms of observable data, so equation (21) in your commit from last night isn't operationalizable yet. Thanks for working on this.
2. On your "clarification question" regarding the Phone Dashboard. I think what you wrote is OK, as long as on the Qualtrics survey we let people tell us *which* apps they want to block. Presumably we would pre-populate a list of possible apps that the person could block (either same list for everyone or, if possible but not necessary, based on the specific apps that the person has on her phone), and then the person would choose which apps she actually wants to block. @gentzkow should also weigh in here in case he has a different vision.
3. I think I lean toward letting people choose which of their own apps they want to block instead of pre-specifying the groups. I suspect that there are only 10-15 apps that most people will want to block (??), and maybe concentrated among 5 (Snapchat, Instagram, a few others), so the survey burden wouldn't be huge, and I think I'd like to see what people choose to do themselves.

**Comment by huntallcott** [comment]
@lenasong per your email I have pushed some additional calculations on non-linear pricing. Take a look at what I did and the comments I left? I think we're close.

**Comment by lenasong** [comment]
@huntallcott thanks for your very helpful comments! We are close - take a look at my updates in sections IV.B.1-3 [here](https://github.com/huntallcott/PhoneAddiction/blob/master/paper/release/PhoneAddiction_Model.pdf).

I worked out identifying demand slope, naivete and cleaned up notations in the nonlinear pricing section. I want to highlight the demand for commitment section again - see Equation 22 for identification of betahat. Let me know if anything is unclear and if you agree with the identification strategy outlined (see Eq 22, 25 and 29).

**Comment by gentzkow** [comment]
@lenasong @huntallcott I still haven't had a time to go back through the nonlinear pricing part of the identification doc carefully but the basic outlines look good. To respond to @huntallcott's original question [here](https://github.com/huntallcott/PhoneAddiction/issues/13#issuecomment-466731489), I am definitely fine with the model being quite stylized in this way and ignoring within-period dynamics. We can always refine further later; for now the priority is to get something that is tractable and transparent. Key question remains whether we are happy enough handling non-linear pricing that we are comfortable setting the usage level at which the subsidy turns on (the kink point) close to average baseline usage.

**Comment by huntallcott** [comment]
@lenasong ,
I think this is just tremendous work.
I especially like how you recognized that g_1(0,betahat) is impossible to observe, and came up with a creative solution to get rid of it between Equation 21 and Equation 22.
As to Matt's key question about how much we need to avoid the non-linear price: I have the general intuition that we want to err on the side of setting the baseline pretty generously. (And remember that this can be person-specific baseline, so we don't need to worry about the relationship to average baseline usage.) The reasons for that intuition are (i) we have to make some assumptions in the doc that people will disagree with and/or ask us to relax, which will be a pain, (ii) even this seemingly tractable model could get difficult as we need to expand the model to be a dynamic model incorporating habit.formation. 
In any event, I don't think we'll settle this until the pilot results come in.
Thanks again Lena for this great work.
I'm provisionally closing this issue thread; let's open other threads as needed to work on dynamics or whatever else.
